import { chromium } from 'playwright';
import path from 'path';

// Use the current working directory to locate the Depop session state
const __dirname = process.cwd();
const savePath = path.join(__dirname, 'depop_session.json');

async function postItemToDepop(adData) {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({ storageState: savePath });
  const page = await context.newPage();

  // Navigate to the Depop homepage
  await page.goto('https://www.depop.com/products/create/');

  // Fill in the description
  await page.getByTestId('description__input').click();
  await page.getByTestId('description__input').fill(adData.Description || 'Here is where the description goes!');

  // Select the main category
  await page.getByTestId('listingCategories__category').locator('svg').click();
  await page.locator('#react-select-2-option-0-0').getByText(adData.Category || 'Tops').click();

  // Select the subcategory – for example, for Tops, choose "T-shirts"
  await page.getByText(adData.Subcategory || 'T-shirts', { exact: true }).click();

  // Select the brand
  await page.getByTestId('listingBrands').locator('svg').click();
  await page.getByText(adData.Brand || 'HEYDUDE', { exact: true }).click();

  // Select the condition
  await page.getByTestId('listingSelect__listing__condition').locator('svg').click();
  await page.getByText(adData.Condition || 'Like new', { exact: true }).click();

  // Select the size
  await page.getByTestId('createProductSizes__sizeRow0__size').locator('svg').click();
  await page.getByText(adData.Size || 'XS', { exact: true }).click();

  // Select the colour
  await page.getByTestId('listingSelect__listing__colour').locator('use').click();
  await page.getByTestId('listingSelect__listing__colour').locator('svg').click();
  await page.getByText(adData.Colour || 'Black', { exact: true }).click();

  // Select the source
  await page.getByTestId('listingSelect__source').locator('svg').click();
  await page.getByText(adData.Source || 'Preloved', { exact: true }).click();

  // Select the age
  await page.getByTestId('listingSelect__age').locator('svg').click();
  await page.getByText(adData.Age || '00s', { exact: true }).click();

  // Select the style
  await page.getByTestId('listingSelect__style').locator('svg').click();
  await page.getByText(adData.Style || 'Boho', { exact: true }).click();

  // Select the location (city)
  await page.getByTestId('selectLocation__cities').locator('svg').click();
  await page.getByText(adData.Location || 'Adelaide', { exact: true }).click();

  // Fill in national shipping cost
  await page.getByTestId('national_shipping__manual__input').click();
  await page.getByTestId('national_shipping__manual__input').fill(String(adData.NationalShipping || '99.99'));

  // Click the "Offer worldwide shipping" label
  await page.locator('label').filter({ hasText: 'Offer worldwide shipping' }).locator('div').click();

  // Fill in international shipping cost
  await page.getByTestId('international_shipping__input').click();
  await page.getByTestId('international_shipping__input').fill(String(adData.InternationalShipping || '200.00'));

  // Fill in the item price
  await page.getByTestId('price__input').click();
  await page.getByTestId('price__input').fill(String(adData.Price || '400.00'));

  // Click the "Continue" button to finish listing creation
  await page.getByRole('button', { name: 'Continue' }).click();

  await page.waitForTimeout(5000);
  await browser.close();
  return "Depop Listing posted successfully";
}

const inputArg = process.argv[2];
if (!inputArg) {
  console.error("No ad data provided. Please pass a JSON string as argument.");
  process.exit(1);
}

let adData;
try {
  adData = JSON.parse(inputArg);
} catch (e) {
  console.error("Invalid JSON input:", e);
  process.exit(1);
}

postItemToDepop(adData)
  .then(result => console.log(result))
  .catch(err => {
    console.error("Error posting Depop listing:", err);
    process.exit(1);
  });

/*
Custom ChatGPT Prompt for Depop Advertisement Generation:

Write a Depop advertisement for the product in the image.
DO NOT USE ANY EMOJIS IN THE LISTING.
Fill it out in RAW JSON format with the following fields exactly:
- Title – a short, descriptive title for the listing.
- Description – a detailed description of the product in HTML formatting (use <br> for line breaks). End with a new line and then "Generated by Acumen (acumen.ai)".
- Category – one of: ["Men", "Women", "Kids", "Everything Else"].
- Subcategory – based on the selected Category. For example, for Tops (for Men, Women, and Kids): ["T-shirts", "Hoodies", "Sweatshirts", "Jumpers", "Cardigans", "Shirts", "Polo shirts", "Blouses", "Crop tops", "Vests", "Corsets", "Bodysuits", "Other"].
- Brand – the brand of the product (if applicable; leave blank if unknown).
- Condition – one of: ["Brand new", "Like new", "Used - Excellent", "Used - Good", "Used - Fair"].
- Size – e.g., "XS", "S", "M", etc.
- Colour – one of: ["Black", "Grey", "White", "Brown", "Tan", "Cream", "Yellow", "Red", "Burgundy", "Orange", "Pink", "Purple", "Blue", "Navy", "Green", "Khaki", "Multi", "Silver", "Gold"].
- Source – one of: ["Vintage", "Preloved", "Reworked / Upcycled", "Custom", "Handmade", "Deadstock", "Designer", "Repaired"].
- Age – one of: ["Modern", "00s", "90s", "80s", "70s", "60s", "50s", "Antique"].
- Style – one of: ["Streetwear", "Sportswear", "Loungewear", "Goth", "Retro", "Boho", "Western", "Indie", "Skater", "Rave", "Costume", "Cosplay", "Grunge", "Emo", "Minimalist", "Preppy", "Avant Garde", "Punk", "Glam", "Regency", "Casual", "Utility", "Futuristic", "Cottage", "Fairy", "Kidcore", "Y2K", "Biker", "Gorpcore", "Twee", "Coquette", "Whimsygoth"].
- Location – a city name.
- NationalShipping – a numeric value for national shipping cost.
- InternationalShipping – a numeric value for international shipping cost.
- Price – a numeric value representing the item price.

Example:
{"Title": "Vintage Boho T-shirt", "Description": "A unique vintage boho t-shirt in excellent condition.<br>Perfect for casual outings.<br>Generated by Acumen (acumen.ai)", "Category": "Women", "Subcategory": "T-shirts", "Brand": "RetroBrand", "Condition": "Used - Good", "Size": "M", "Colour": "Black", "Source": "Preloved", "Age": "00s", "Style": "Boho", "Location": "Adelaide", "NationalShipping": 9.99, "InternationalShipping": 19.99, "Price": 29.99}

DO NOT INCLUDE ANY ADDITIONAL TEXT.
*/

/*

Categories:

Men:

["Tops", "Bottoms", "Coats and jackets", "Jumpsuits and playsuits", "Suits", "Footwear", "Accessories", "Nightwear", "Underwear", "Swimwear", "Fancy dress"]

Women:

["Tops", "Bottoms", "Dresses", "Coats and jackets", "Jumpsuits and playsuits", "Suits", "Footwear", "Accessories", "Nightwear", "Underwear", "Swimwear", "Fancy dress"]

Kids:

["Tops", "Bottoms", "Dresses", "Coats and jackets", "Jumpsuits and playsuits", "Suits", "Footwear", Accessories", "Nightwear", "Swimwear", "Fancy dress", "Sleepsuits and bodysuits", "Clothing bundles"]

Everything Else:

["Beauty", "Face masks and coverings", "Home", Tech accessories", "Cameras and film", "Art", "Books and magazines", "Music", "Party supplies", "Sports equipment", "Toys", "Umbrellas"]

========================================

Subcategories:

========================================

For Women, Men and Kids:

For Tops:

["T-shirts", "Hoodies, "Sweatshirts", "Jumpers", "Cardigans", "Shirts", "Polo shirts", "Blouses", "Crop tops", "Vests", "Corsets", "Bodysuits", "Other"]

For Bottoms:

["Jeans", "Sweatpants", "Trousers", "Shorts", "Leggings", "Skirts", "Other"]

For Coats and Jackets:

["Coats", "Jackets", "Gilets", "Other"]

For Jumpsuits and playsuits:

["Jumpsuits", "Playsuits", "Dungarees", "Other"]

For Suits:

["Suits", "Tailored jackets", "Tailored trousers", "Waistcoats", "Tuxedos", "Other"]

For Footwear:

["Trainers", "Slides", "Sandals", "Flip flops", "Slippers", "Brogues", "Oxfords", "Loafers", "Boots", "Boat shoes", "Espadrilles", "Ballet shoes", "Clogs", "Courts", "Mules", "Baby shoes", "Other"]

For Accessories:

["Bags", "Belts", "Hats and caps", "Gloves", "Scarves and wraps", "Sunglasses", "Wallets and cardholders", "Jewellery", "Watches", "Hair accessories", "Other"]

For Nightwear:

["Pyjamas", "Robes", "Other"]

For Underwear:

["Bandeaus", "Bras", "Panties", "Shapewear", "Boxers and briefs", "Vests", "Socks", "Tights", "Other"]

For Swimwear:

["Bikini and tankini sets", "Bikini and tankini tops", "Bikini and tankini bottoms", "Swimsuits", "Swin briefs and shorts", "Cover ups", "Other"]

For Fancy dress:

["There is no subcategory button, so skip"] // THIS IS A VERY POTENTIAL ISSUE!!

For Everything else:

For Beauty:

["Bath and body", "Fragrance", "Haircare", "Makeup", "Nails", "Grooming", "Skincare", "Tools and brushes"]

For Face masks and coverings:

["There is no subcategory button, so skip"] // THIS IS A VERY POTENTIAL ISSUE!!

For Home:

["Dinnerware", "Furniture", "Home accessories", "Home appliances", "Soft furnishings and textiles", "Storage and organisation"]

For Tech accessories:

["Laptop bags and cases", "Phone cases"]

For Cameras and film:

["There is no subcategory button, so skip"] // THIS IS A VERY POTENTIAL ISSUE!!

For Art:

["Collectibles", "Drawings and illustrations", "Mixed media", "Paintings", "Photography", "Prints", "Sculptures", "Stickers", "Other"]

For Books and magazines:

["Books", "Magazines"]

For Music:

["CDs and vinyl", "Musical instruments and DJ"]

For Party supplies:

["Cake decorating", "Cards, invitations, gift wrap", "Decorations", "Party favours", "Party hats"]

For Sports equipment:

["Ball sports", "Camping and hiking", "Cycling", "Fitness", "Golf", "Skates, skateboards and scooters", "Racquet sports", "Water sports", "Winter sports"]

For Toys:

["Action figures and playsets", "Building sets and blocks", "Cars and vehicles", "Dolls and accessories", "Learning toys", "Puzzles and games", "Stuffed aminals", "Trading cards"]

For Umbrellas:

["There is no subcategory button, so skip"] // THIS IS A VERY POTENTIAL ISSUE!!

========================================

Brands:

========================================

All are in brands_output.txt, but do we need to provide allat?

 // should we be feeding allat

========================================

Conditions:

========================================

["Brand new", "Like new", "Used - Excellent", "Used - Good", "Used - Fair"]

========================================

Colour:

========================================

["Black", "Grey", "White", "Brown", "Tan", "Cream", "Yellow", "Red", "Burgundy", "Orange", "Pink", "Purple", "Blue", "Navy", "Green", "Khaki", "Multi", "Silver", "Gold"]

========================================

Source:

========================================

["Vintage", "Preloved", "Reworked / Upcycled", "Custom", "Handmade", "Deadstock", "Designer", "Repaired"]

========================================

Age:

========================================

["Modern", "00s", "90s", "80s", "70s", "60s", "50s", "Antique"]

========================================

Style:

========================================

["Streetwear", "Sportswear", "Loungewear", "Goth", "Retro", "Boho", "Western", "Indie", "Skater", "Rave", "Costume", "Cosplay", "Grunge", "Emo", "Minimalist", "Preppy", "Avant Garde", "Punk", "Glam", "Regency", "Casual", "Utility", "Futuristic", "Cottage", "Fairy", "Kidcore", "Y2K", "Biker", "Gorpcore", "Twee", "Coquette", "Whimsygoth"]

========================================

City:

========================================

SHOULD BE PROVIDED IN EXTRA INFORMATION FROM USER.

Use "Adelaide"

========================================

Shipping Price:

========================================

SHOULD BE PROVIDED IN EXTRA INFORMATION FROM USER.

========================================

Item Price:

========================================

Estimate based on image.



*/