import express from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import OpenAI from 'openai';
import { chromium } from 'playwright';
import dotenv from 'dotenv';
import path from 'path';
import { exec } from 'child_process'; // for executing scripts
dotenv.config();

const app = express();
const port = 5500;

app.use(bodyParser.json({ limit: '25mb' }));
app.use(bodyParser.urlencoded({ limit: '25mb', extended: true }));
app.use(cors());
app.use(express.json());

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

app.post('/analyze', async (req, res) => {
  const { imageData } = req.body;
  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: `
                Write a facebook marketplace Advertisement based on the product in the image.

                DO NOT USE ANY EMOJIS IN THE LISTING.

                Fill it out in JSON format with the following fields:
                - Title – a short, descriptive title for the listing.
                - Price – a price estimate for the product in AUD.
                - Category – choose the most suitable category from:
                  ["Tools", "Furniture", "Household", "Garden", "Appliances", 
                  "Video Games", "Books, Films & Music",
                  "Bags & Luggage", "Women's clothing & shoes", "Men's clothing & shoes", "Jewellery and accessories",
                  "Health & Beauty", "Pet supplies", "Baby & children", "Toys and games",
                  "Electronics & computers", "Mobile phones",
                  "Bicycles", "Arts & crafts", "Sport and outdoors", "Car parts", "Musical Instruments", "Antiques and collectibles",
                  "Garage sale", "Miscellaneous", "Vehicles"]
                - Condition – one of: ["New", "Used – like new", "Used – good", "Used – fair"]
                - Brand – the brand of the product (if applicable; leave blank if unknown)
                - Description – a detailed description of the product. At the end include a new line, and then "Generated by Acumen (acumen.ai)"
                - Availability – one of: ["List as single item", "List as in stock"]
                - Product Tags – a list of tags for the product.
                - Meetup Preferences – a list of meetup preferences, choose from: ["Public meetup", "Door pick-up", "Door drop-off"]
                - Hide from friends – a boolean value.

                OUTPUT RAW TEXT OUTPUT.

                EG.

                { "Title": "Casio FX-CG50 Graphing Calculator", "Price": 120, "Category": "Electronics & computers", "Condition": "Used – like new", "Brand": "Casio", "Description": "Lightly used Casio FX-CG50 graphing calculator in excellent condition. Perfect for students and professionals needing advanced calculation capabilities. Comes with original packaging, USB cable, and user manuals. Generated by Acumen (acumen.ai)", "Availability": "List as single item", "Product Tags": ["Calculator", "Graphing", "Casio", "FX-CG50", "Math"], "Meetup Preferences": ["Public meetup", "Door pick-up"], "Hide from friends": false }
                
                DO NOT SPECIFY IT IS A JSON WITH ANY EXTRA TEXT.
            ` },
            { type: 'image_url', image_url: { url: `data:image/jpeg;base64,${imageData}` } }
          ]
        }
      ],
      max_tokens: 300
    });
    const answer = response.choices[0].message.content;
    res.json({ response: answer });
  } catch (error) {
    console.error('Error analyzing image:', error);
    res.status(500).json({ error: 'Error analyzing image' });
  }
});

// new endpoint for eBay advertisement analysis
app.post('/analyze-ebay', async (req, res) => {
  const { imageData } = req.body;
  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: `
                    Write an eBay advertisement for the product in the image.

                    DO NOT USE ANY EMOJIS IN THE LISTING.

                    Fill it out in RAW JSON format with the following fields exactly:
                    - Title – a short, descriptive title for the listing.
                    - Price – a price estimate for the product in AUD.
                    - Condition for different Categories – one of:

                        For Calculators and Electronics:
                          ["Brand New", "New: Never Used", "Seller refurbished", "Used", "For parts or not working"].

                        For Hats:
                          ["New with tags", "New without tags", "New with defects", "Pre-Owned"].

                        For Shoes:
                          ["New with box", "New without box", "New with Imperfections", "Pre-owned"].

                        For Books:
                          ["Brand New", "Like New", "Very Good", "Good", "Acceptable"].

                        For Clothing:
                          ["New with tags", "New without tags", "New with defects", "Pre-Owned"].

                        For Video Games:
                          ["Brand New", "New: Never Used", "Used", "For parts or not working"].

                        For Watches:
                          ["Brand New", "Pre-owned", "Certified Pre-owned", "For parts or not working"].

                        For Furniture:
                          ["New", "Used"].

                        For Collectibles:
                          ["Brand New", "Used", "For parts or not working"].

                    - Description – a detailed description of the product in HTML formatting (use <br> for line breaks). End with a new line and then "Generated by Acumen (acumen.ai)".
                    - SearchTerm – a concise term to be used for searching the product on eBay.

                    EG.

                    { "Title": "Casio FX-CG50 Calculator", "Price": 99.99, "Condition": "Used", "Description": "Lightly used Casio FX-CG50 calculator in good working condition.<br>Perfect for students and professionals.<br>Generated by Acumen (acumen.ai)", "SearchTerm": "Casio FX-CG50 Calculator" }

                    DO NOT SPECIFY IT IS A JSON WITH ANY EXTRA TEXT EG DO NOT SAY "JSON Grave (DASH) Grave (DASH) Grave (DASH)" AND THEN THE JSON. JUST OUTPUT RAW JSON AS TEXT.
                    
                    LIKE THIS:

                    {"Title": "Casio FX-CG50 Calculator with Accessories", "Price": 120.00, "Condition": "Used", "Description": "Casio FX-CG50 calculator in good condition, includes original packaging and manuals.<br>Comes with cables and protective cover.<br>Ideal for students and professionals seeking a reliable graphing calculator.<br>Generated by Acumen (acumen.ai)", "SearchTerm": "Casio FX-CG50 Calculator" }

                    SEE, NO DASHES. DO NOT INCLUDE ´´´ JSON OR I WILL TERMINATE YOU

                    DO NOT INCLUDE ANY ADDITIONAL TEXT. CONDITION SHOULD BE THE EXACT SAME TEXT AS CONDITIONS FROM THE ARRAY STATES ABOVE.
            ` },
            { type: 'image_url', image_url: { url: `data:image/jpeg;base64,${imageData}` } }
          ]
        }
      ],
      max_tokens: 300
    });
    const answer = response.choices[0].message.content;
    res.json({ response: answer });
  } catch (error) {
    console.error('Error analyzing image for eBay:', error);
    res.status(500).json({ error: 'Error analyzing image for eBay' });
  }
});

// new endpoint for Depop advertisement analysis
app.post('/analyze-depop', async (req, res) => {
  const { imageData } = req.body;
  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: `
                    Write a Depop advertisement for the product in the image.
                    
                    DO NOT USE ANY EMOJIS IN THE LISTING.
                    
                    Fill it out in RAW JSON format with the following fields exactly:
                    - Title – a short, descriptive title for the listing.
                    - Description – a detailed description of the product in HTML formatting (use <br> for line breaks). End with a new line and then "Generated by Acumen (acumen.ai)".
                    - Category – one of: REFER TO BELOW CATEGORIES
                    - Subcategory – based on the selected Category. For example, for Tops: ["T-shirts", "Hoodies", "Sweatshirts", "Jumpers", "Cardigans", "Shirts", "Polo shirts", "Blouses", "Crop tops", "Vests", "Corsets", "Bodysuits", "Other"].
                    - Brand – the brand of the product (if applicable; leave blank if unknown).
                    - Condition – one of: ["Brand new", "Like new", "Used - Excellent", "Used - Good", "Used - Fair"].
                    - Size – e.g., "XS", "S", "M", etc.
                    - Colour – one of: ["Black", "Grey", "White", "Brown", "Tan", "Cream", "Yellow", "Red", "Burgundy", "Orange", "Pink", "Purple", "Blue", "Navy", "Green", "Khaki", "Multi", "Silver", "Gold"].
                    - Source – one of: ["Vintage", "Preloved", "Reworked / Upcycled", "Custom", "Handmade", "Deadstock", "Designer", "Repaired"].
                    - Age – one of: ["Modern", "00s", "90s", "80s", "70s", "60s", "50s", "Antique"].
                    - Style – one of: ["Streetwear", "Sportswear", "Loungewear", "Goth", "Retro", "Boho", "Western", "Indie", "Skater", "Rave", "Costume", "Cosplay", "Grunge", "Emo", "Minimalist", "Preppy", "Avant Garde", "Punk", "Glam", "Regency", "Casual", "Utility", "Futuristic", "Cottage", "Fairy", "Kidcore", "Y2K", "Biker", "Gorpcore", "Twee", "Coquette", "Whimsygoth"].
                    - Location – a city name.
                    - NationalShipping – a numeric value for national shipping cost.
                    - InternationalShipping – a numeric value for international shipping cost.
                    - Price – a numeric value representing the item price.

                    Categories:

                      M

                      ["Tops", "Bottoms", "Coats and jackets", "Jumpsuits and playsuits", "Suits", "Footwear", "Accessories", "Nightwear", "Underwear", "Swimwear", "Fancy dress"]

                      F

                      ["Tops", "Bottoms", "Dresses", "Coats and jackets", "Jumpsuits and playsuits", "Suits", "Footwear", "Accessories", "Nightwear", "Underwear", "Swimwear", "Fancy dress"]

                      K

                      ["Tops", "Bottoms", "Dresses", "Coats and jackets", "Jumpsuits and playsuits", "Suits", "Footwear", Accessories", "Nightwear", "Swimwear", "Fancy dress", "Sleepsuits and bodysuits", "Clothing bundles"]

                      AAO

                      ["Beauty", "Face masks and coverings", "Home", Tech accessories", "Cameras and film", "Art", "Books and magazines", "Music", "Party supplies", "Sports equipment", "Toys", "Umbrellas"]

                      ========================================

                      Subcategories:

                      ========================================

                      For Women, Men and Kids:

                      For Tops:

                      ["T-shirts", "Hoodies, "Sweatshirts", "Jumpers", "Cardigans", "Shirts", "Polo shirts", "Blouses", "Crop tops", "Vests", "Corsets", "Bodysuits", "Other"]

                      For Bottoms:

                      ["Jeans", "Sweatpants", "Trousers", "Shorts", "Leggings", "Skirts", "Other"]

                      For Coats and Jackets:

                      ["Coats", "Jackets", "Gilets", "Other"]

                      For Jumpsuits and playsuits:

                      ["Jumpsuits", "Playsuits", "Dungarees", "Other"]

                      For Suits:

                      ["Suits", "Tailored jackets", "Tailored trousers", "Waistcoats", "Tuxedos", "Other"]

                      For Footwear:

                      ["Trainers", "Slides", "Sandals", "Flip flops", "Slippers", "Brogues", "Oxfords", "Loafers", "Boots", "Boat shoes", "Espadrilles", "Ballet shoes", "Clogs", "Courts", "Mules", "Baby shoes", "Other"]

                      For Accessories:

                      ["Bags", "Belts", "Hats and caps", "Gloves", "Scarves and wraps", "Sunglasses", "Wallets and cardholders", "Jewellery", "Watches", "Hair accessories", "Other"]

                      For Nightwear:

                      ["Pyjamas", "Robes", "Other"]

                      For Underwear:

                      ["Bandeaus", "Bras", "Panties", "Shapewear", "Boxers and briefs", "Vests", "Socks", "Tights", "Other"]

                      For Swimwear:

                      ["Bikini and tankini sets", "Bikini and tankini tops", "Bikini and tankini bottoms", "Swimsuits", "Swin briefs and shorts", "Cover ups", "Other"]

                      For Fancy dress:

                      ["There is no subcategory button, so skip"] // THIS IS A VERY POTENTIAL ISSUE!!

                      For Everything else:

                      For Beauty:

                      ["Bath and body", "Fragrance", "Haircare", "Makeup", "Nails", "Grooming", "Skincare", "Tools and brushes"]

                      For Face masks and coverings:

                      ["There is no subcategory button, so skip"] // THIS IS A VERY POTENTIAL ISSUE!!

                      For Home:

                      ["Dinnerware", "Furniture", "Home accessories", "Home appliances", "Soft furnishings and textiles", "Storage and organisation"]

                      For Tech accessories:

                      ["Laptop bags and cases", "Phone cases"]

                      For Cameras and film:

                      ["There is no subcategory button, so skip"] // THIS IS A VERY POTENTIAL ISSUE!!

                      For Art:

                      ["Collectibles", "Drawings and illustrations", "Mixed media", "Paintings", "Photography", "Prints", "Sculptures", "Stickers", "Other"]

                      For Books and magazines:

                      ["Books", "Magazines"]

                      For Music:

                      ["CDs and vinyl", "Musical instruments and DJ"]

                      For Party supplies:

                      ["Cake decorating", "Cards, invitations, gift wrap", "Decorations", "Party favours", "Party hats"]

                      For Sports equipment:

                      ["Ball sports", "Camping and hiking", "Cycling", "Fitness", "Golf", "Skates, skateboards and scooters", "Racquet sports", "Water sports", "Winter sports"]

                      For Toys:

                      ["Action figures and playsets", "Building sets and blocks", "Cars and vehicles", "Dolls and accessories", "Learning toys", "Puzzles and games", "Stuffed aminals", "Trading cards"]

                      For Umbrellas:

                      ["There is no subcategory button, so skip"] // THIS IS A VERY POTENTIAL ISSUE!!

                      ========================================

                      Brands:

                      ========================================

                      All are in brands_output.txt, but do we need to provide allat?

                      // should we be feeding allat

                      ========================================

                      Conditions:

                      ========================================

                      ["Brand new", "Like new", "Used - Excellent", "Used - Good", "Used - Fair"]

                      ========================================

                      Colour:

                      ========================================

                      ["Black", "Grey", "White", "Brown", "Tan", "Cream", "Yellow", "Red", "Burgundy", "Orange", "Pink", "Purple", "Blue", "Navy", "Green", "Khaki", "Multi", "Silver", "Gold"]

                      ========================================

                      Source:

                      ========================================

                      ["Vintage", "Preloved", "Reworked / Upcycled", "Custom", "Handmade", "Deadstock", "Designer", "Repaired"]

                      ========================================

                      Age:

                      ========================================

                      ["Modern", "00s", "90s", "80s", "70s", "60s", "50s", "Antique"]

                      ========================================

                      Style:

                      ========================================

                      ["Streetwear", "Sportswear", "Loungewear", "Goth", "Retro", "Boho", "Western", "Indie", "Skater", "Rave", "Costume", "Cosplay", "Grunge", "Emo", "Minimalist", "Preppy", "Avant Garde", "Punk", "Glam", "Regency", "Casual", "Utility", "Futuristic", "Cottage", "Fairy", "Kidcore", "Y2K", "Biker", "Gorpcore", "Twee", "Coquette", "Whimsygoth"]

                      ========================================

                      City:

                      ========================================

                      SHOULD BE PROVIDED IN EXTRA INFORMATION FROM USER.

                      Use "Adelaide"

                      ========================================

                      Shipping Price:

                      ========================================

                      SHOULD BE PROVIDED IN EXTRA INFORMATION FROM USER.

                      ========================================

                      Item Price:

                      ========================================

                      Estimate based on image.
                    
                    Example:
                    {"Title": "Vintage Boho T-shirt", "Description": "A unique vintage boho t-shirt in excellent condition.<br>Perfect for casual outings.<br>Generated by Acumen (acumen.ai)", "Category": "Women", "Subcategory": "T-shirts", "Brand": "RetroBrand", "Condition": "Used - Good", "Size": "M", "Colour": "Black", "Source": "Preloved", "Age": "00s", "Style": "Boho", "Location": "Adelaide", "NationalShipping": 9.99, "InternationalShipping": 19.99, "Price": 29.99}
                    
                    DO NOT INCLUDE ANY ADDITIONAL TEXT. DO NOT INCLUDE ´´´ JSON OR I WILL TERMINATE YOU
            ` },
            { type: 'image_url', image_url: { url: `data:image/jpeg;base64,${imageData}` } } // fix prompt its so bad lmao
            // SO MANY ISSUES, ITS BECAUSE OF HOW COMPLEX THIS IS AND HOW SIMPLE AUTOMATION IS
          ]
        }
      ],
      max_tokens: 300
    });
    const answer = response.choices[0].message.content;
    res.json({ response: answer });
  } catch (error) {
    console.error('Error analyzing image for Depop:', error);
    res.status(500).json({ error: 'Error analyzing image for Depop' });
  }
});

// facebook posting endpoint (unchanged)
async function postListing(adData) {
  const savePath = path.join(process.cwd(), 'facebook_session.json');
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({ storageState: savePath });
  const page = await context.newPage();

  await page.goto("https://www.facebook.com/");
  await page.getByRole('link', { name: 'Marketplace' }).click();
  await page.getByRole('link', { name: 'Create new listing' }).click();
  await page.getByRole('link', { name: 'Item for sale Create a single' }).click();

  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill(adData.Title || "");

  await page.getByRole('textbox', { name: 'Price' }).click();
  await page.getByRole('textbox', { name: 'Price' }).fill(adData.Price ? String(adData.Price) : "");

  await page.getByRole('button', { name: 'Category' }).click();
  await page.getByRole('button', { name: adData.Category || "", exact: true }).click();

  await page.getByRole('combobox', { name: 'Condition' }).locator('div').nth(2).click();
  await page.getByRole('option', { name: adData.Condition || 'Used – good', exact: true }).click();

  await page.getByRole('textbox', { name: 'Brand' }).click();
  await page.getByRole('textbox', { name: 'Brand' }).fill(adData.Brand || "");

  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill(adData.Description || "");

  await page.getByRole('combobox', { name: 'Availability' }).locator('div').nth(2).click();
  await page.getByText(adData.Availability || 'List as single item').click();

  await page.getByRole('textbox', { name: 'Product tags' }).click();
  const productTags = Array.isArray(adData["Product Tags"])
    ? adData["Product Tags"].join(', ')
    : (adData["Product Tags"] || "");
  await page.getByRole('textbox', { name: 'Product tags' }).fill(productTags);

  if (
    adData["Meetup Preferences"] &&
    Array.isArray(adData["Meetup Preferences"]) &&
    adData["Meetup Preferences"].includes("Door pick-up")
  ) {
    await page.getByRole('checkbox', { name: 'Door pick-up Buyer picks up' }).click();
  }

  await page.getByRole('button', { name: 'Next' }).click();
  await page.waitForTimeout(5000);
  await browser.close();
  return "Listing posted successfully";
}

app.post('/post-facebook', async (req, res) => {
  const adData = req.body;
  try {
    const result = await postListing(adData);
    res.json({ success: result });
  } catch (error) {
    console.error('Error posting Facebook listing:', error);
    res.status(500).json({ error: error.toString() });
  }
});

// new endpoint for eBay posting
app.post('/post-ebay', async (req, res) => {
  const adData = req.body;
  try {
    const adDataStr = JSON.stringify(adData);
    exec(`node ebay_post.spec.js '${adDataStr}'`, (error, stdout, stderr) => {
      if (error) {
         console.error(`Error executing ebay_post.spec.js: ${error}`);
         return res.status(500).send(stderr);
      }
      res.send(stdout);
    });
  } catch (error) {
    console.error('Error posting eBay listing:', error);
    res.status(500).json({ error: error.toString() });
  }
});

// new endpoint for Depop posting
app.post('/post-depop', async (req, res) => {
  const adData = req.body;
  try {
    const adDataStr = JSON.stringify(adData);
    exec(`node depop_post.spec.js '${adDataStr}'`, (error, stdout, stderr) => {
      if (error) {
         console.error(`Error executing depop_post.spec.js: ${error}`);
         return res.status(500).send(stderr);
      }
      res.send(stdout);
    });
  } catch (error) {
    console.error('Error posting Depop listing:', error);
    res.status(500).json({ error: error.toString() });
  }
});

// CONNECTIONS TO PLATFORMS

app.get('/run-fb-login', (req, res) => {
  exec('node fb_login.spec.js', (error, stdout, stderr) => {
    if (error) {
      console.error(`Error executing fb_login.spec.js: ${error}`);
      return res.status(500).send(stderr);
    }
    res.send(stdout);
  });
});

app.get('/run-ebay-login', (req, res) => {
  exec('node ebay_login.spec.js', (error, stdout, stderr) => {
    if (error) {
      console.error(`Error executing ebay_login.spec.js: ${error}`);
      return res.status(500).send(stderr);
    }
    res.send(stdout);
  });
});

app.get('/run-depop-login', (req, res) => {
  exec('node depop_login.spec.js', (error, stdout, stderr) => {
    if (error) {
      console.error(`Error executing depop_login.spec.js: ${error}`);
      return res.status(500).send(stderr);
    }
    res.send(stdout);
  });
});

app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});