import express from 'express';
import cors from 'cors';
import bodyParser from 'body-parser';
import OpenAI from 'openai';
import { chromium } from 'playwright';
import dotenv from 'dotenv';
import path from 'path';
import { exec } from 'child_process'; // NEW: Import child_process for executing scripts
dotenv.config();

const app = express();
const port = 5500;

app.use(bodyParser.json({ limit: '25mb' }));
app.use(bodyParser.urlencoded({ limit: '25mb', extended: true }));
app.use(cors());
app.use(express.json());

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

app.post('/analyze', async (req, res) => {
  const { imageData } = req.body;
  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: `

                Write a facebook marketplace Advertisement based on the product in the image.

                DO NOT USE ANY EMOJIS IN THE LISTING.

                Fill it out in JSON format with the following fields:
                - Title – a short, descriptive title for the listing.
                - Price – a price estimate for the product in AUD.
                - Category – choose the most suitable category from:
                  ["Tools", "Furniture", "Household", "Garden", "Appliances", 
                  "Video Games", "Books, Films & Music",
                  "Bags & Luggage", "Women's clothing & shoes", "Men's clothing & shoes", "Jewellery and accessories",
                  "Health & Beauty", "Pet supplies", "Baby & children", "Toys and games",
                  "Electronics & computers", "Mobile phones",
                  "Bicycles", "Arts & crafts", "Sport and outdoors", "Car parts", "Musical Instruments", "Antiques and collectibles",
                  "Garage sale", "Miscellaneous", "Vehicles"]
                - Condition – one of: ["New", "Used – like new", "Used – good", "Used – fair"]
                - Brand – the brand of the product (if applicable; leave blank if unknown)
                - Description – a detailed description of the product. At the end include a new line, and then "Generated by Acumen (acumen.ai)"
                - Availability – one of: ["List as single item", "List as in stock"]
                - Product Tags – a list of tags for the product.
                - Meetup Preferences – a list of meetup preferences, choose from: ["Public meetup", "Door pick-up", "Door drop-off"]
                - Hide from friends – a boolean value.

                OUTPUT RAW TEXT OUTPUT.

                EG.

                { "Title": "Casio FX-CG50 Graphing Calculator", "Price": 120, "Category": "Electronics & computers", "Condition": "Used – like new", "Brand": "Casio", "Description": "Lightly used Casio FX-CG50 graphing calculator in excellent condition. Perfect for students and professionals needing advanced calculation capabilities. Comes with original packaging, USB cable, and user manuals. Generated by Acumen (acumen.ai)", "Availability": "List as single item", "Product Tags": ["Calculator", "Graphing", "Casio", "FX-CG50", "Math"], "Meetup Preferences": ["Public meetup", "Door pick-up"], "Hide from friends": false }

                NOT.

                DASH DASH DASH JSON { "Title": "Casio FX-CG50 Graphing Calculator", "Price": 120, "Category": "Electronics & computers", "Condition": "Used – like new", "Brand": "Casio", "Description": "Lightly used Casio FX-CG50 graphing calculator in excellent condition. Perfect for students and professionals needing advanced calculation capabilities. Comes with original packaging, USB cable, and user manuals. Generated by Acumen (acumen.ai)", "Availability": "List as single item", "Product Tags": ["Calculator", "Graphing", "Casio", "FX-CG50", "Math"], "Meetup Preferences": ["Public meetup", "Door pick-up"], "Hide from friends": false } DASH DASH DASH

                DO NOT SPECIFY IT IS A JSON WITH THOSE DASHES. USE ONLY THE SPECIFIED CATEGORIES, WORD FOR WORD.

            `},
            { type: 'image_url', image_url: { url: `data:image/jpeg;base64,${imageData}` } }
          ]
        }
      ],
      max_tokens: 300
    });

    const answer = response.choices[0].message.content;
    res.json({ response: answer });
  } catch (error) {
    console.error('Error analyzing image:', error);
    res.status(500).json({ error: 'Error analyzing image' });
  }
});

async function postListing(adData) {
  const savePath = path.join(process.cwd(), 'facebook_session.json');
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({ storageState: savePath });
  const page = await context.newPage();

  // ASSUMING SIGN IN IS DONE
  // Adi we need to incorporate this being not clickable unless user is signed in

  await page.goto("https://www.facebook.com/");
  await page.getByRole('link', { name: 'Marketplace' }).click();
  await page.getByRole('link', { name: 'Create new listing' }).click();
  await page.getByRole('link', { name: 'Item for sale Create a single' }).click();

  // title
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('textbox', { name: 'Title' }).fill(adData.Title || "");

  // price
  await page.getByRole('textbox', { name: 'Price' }).click();
  await page.getByRole('textbox', { name: 'Price' }).fill(adData.Price ? String(adData.Price) : "");

  // category: click the category button and then select the category from adData
  await page.getByRole('button', { name: 'Category' }).click();
  await page.getByRole('button', { name: adData.Category || "", exact: true }).click();

  // condition: open combobox and select the condition -> nth is the child of the box
  await page.getByRole('combobox', { name: 'Condition' }).locator('div').nth(2).click();
  await page.getByRole('option', { name: adData.Condition || 'Used – good', exact: true }).click();

  // brand
  await page.getByRole('textbox', { name: 'Brand' }).click();
  await page.getByRole('textbox', { name: 'Brand' }).fill(adData.Brand || "");

  // description
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill(adData.Description || "");

  // availability -> open combobox and select the appropriate option
  await page.getByRole('combobox', { name: 'Availability' }).locator('div').nth(2).click();
  await page.getByText(adData.Availability || 'List as single item').click();

  // tags 4 product
  await page.getByRole('textbox', { name: 'Product tags' }).click();
  const productTags = Array.isArray(adData["Product Tags"])
    ? adData["Product Tags"].join(', ')
    : (adData["Product Tags"] || "");
  await page.getByRole('textbox', { name: 'Product tags' }).fill(productTags);

  // meetup Preferences: if "Door pick-up" is one of the preferences, click its checkbox
  if (
    adData["Meetup Preferences"] &&
    Array.isArray(adData["Meetup Preferences"]) &&
    adData["Meetup Preferences"].includes("Door pick-up")
  ) {
    await page.getByRole('checkbox', { name: 'Door pick-up Buyer picks up' }).click();
  }

  // next button
  await page.getByRole('button', { name: 'Next' }).click();

  // IM NOT SURE WHAT TO DO AFTER THIS BECAUSE FACEBOOK ACCOUNT IS SAYING MAX LISTINGS IS REACHED
  // ALSO IMAGE UPLOAD. DO WE NEED TO STORE UPLOADED IMAGE LOCALLY???

  await page.waitForTimeout(5000);

  await browser.close();
  return "Listing posted successfully";
}

app.post('/post-facebook', async (req, res) => {
  const adData = req.body;
  try {
    const result = await postListing(adData);
    res.json({ success: result });
  } catch (error) {
    console.error('Error posting Facebook listing:', error);
    res.status(500).json({ error: error.toString() });
  }
});

//// CONNECTIONS TO PLATFORMS ////

// connect to fb button clicked
app.get('/run-fb-login', (req, res) => {
  let FB_authenticated = true; // this is for confirmation that it is confirmed
  exec('node fb_post.login.js', (error, stdout, stderr) => {
    if (error) {
      console.error(`Error executing authentication process: ${error}`);
      return res.status(500).send(stderr);
    }
    res.send(stdout);
  });
});

// connect to eb button clicked
app.get('/run-ebay-login', (req, res) => {
  let EBAY_authenticated = true;
  exec('node ebay_login.spec.js', (error, stdout, stderr) => {
    if (error) {
      console.error(`Error executing authentication process: ${error}`);
      return res.status(500).send(stderr);
    }
    res.send(stdout);
  });
});

app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});